version: '3.8'

services:
  vue-frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    links:
      - flask-app
      - mongodb

  flask-app:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    build: ./mongodb
    ports:
      - "27018:27017"